# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "daily"
    directories: 
      - "docs/src/BcdiCore.jl"
      - "docs/src/BcdiTrad.jl"
      - "docs/src/BcdiStrain.jl"
      - "docs/src/BcdiMeso.jl"
