name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@main
        with:
          repository: byu-cxi/BcdiCore.jl
          path: ./docs/src/BcdiCore.jl
      - uses: actions/checkout@main
        with:
          repository: byu-cxi/BcdiTrad.jl
          path: ./docs/src/BcdiTrad.jl
      - uses: actions/checkout@main
        with:
          repository: byu-cxi/BcdiStrain.jl
          path: ./docs/src/BcdiStrain.jl
      - uses: actions/checkout@main
        with:
          repository: byu-cxi/BcdiMeso.jl
          path: ./docs/src/BcdiMeso.jl
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); Pkg.develop(path="docs/src/BcdiTrad.jl"); Pkg.develop(path="docs/src/BcdiStrain.jl"); Pkg.develop(path="docs/src/BcdiMeso.jl"); Pkg.instantiate()'
      - name: Build and deploy
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
